services:
  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - ./secrets/firebase-key.json:/app/firebase-key.json:ro
    command: >
      sh -c "npm ci && nodemon index.js"
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: byebye
      REDIS_HOST: redis
      JWT_SECRET: dev-secret
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: byebye
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
