# docker-compose.prod.yml
services:
  api:
    build:
      context: .
      target: prod
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: byebye
  redis:
    image: redis:7
    ports: ["6379:6379"]
volumes:
  pgdata:
