name: Deploy to Server

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/anrigerlife/byebye-chat-backend
            git pull origin main
            npm install
            pm2 restart chat-app
